name: CI

on:
  push:
    branches:
      - main
      - fbarriga/*
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: temurin
          cache: maven
      - name: Build and verify
        run: mvn clean install package
